### ISSUE TITLE
does it support the case class attributes are also case class?

### ISSUE THREAD

**Issue by vivafung** [mkorman9/scala-dynamodb-mapper#1]
hello. I came across to this library and thinking it might help me in my work. but i have a question:
so instead of the case class model Cat, what if my customized case class is something like:
case class AAA(x: Oldid, y: NewId, z: TxnInput, h: NonTxnInput)
whereas Oldid, NewId, TxnInput, NonTxnInput are also case classes that i hv defined. how does this mapper can work with this scenario?  
looking forward your reply. thank you!

**Comment by mkorman9** [comment]
Hello,

as far as I know, DynamoDB[ does not support complex types](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html), and most common approach is to save nested objects as JSON strings or [join two tables](https://stackoverflow.com/questions/11443700/is-it-a-good-idea-to-store-an-object-in-amazon-dynamo-as-json). Currently strategy for complex objects persistence isn't implemented in library.

**Comment by mkorman9** [comment]
Support for JSON serialization has been introduced in version 0.7 - https://github.com/mkorman9/scala-dynamodb-mapper/pull/6

It is described on wiki - https://github.com/mkorman9/scala-dynamodb-mapper/wiki/5.-How-to-map-complex-objects%3F
